/**
 * Print / Save as PDF (BLOCKS.md §7.4): a print root directly under <body> carrying the
 * light tokens inline, the @media print / @page A4 hooks, static block renderers (data
 * tables visible, no menus), defanged content by default, then `window.print()` and an
 * unmount on `afterprint`. jsdom cannot print; the portal content and CSS hooks are the
 * contract.
 */
import { act, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import { buildReportDoc } from '../model';
import { PRINT_CSS, PRINT_ROOT_ID, clearPrintRoot, printDocument } from '../export/print';
import { REPORT_LIGHT_TOKENS } from '../export/report-tokens';
import { NOW, sampleReport } from './fixtures';

const doc = () => buildReportDoc(sampleReport(), { author: 'ana', appVersion: '0.1.13', generatedAt: NOW.toISOString() });

let print: ReturnType<typeof vi.fn>;
beforeEach(() => {
  print = vi.fn();
  Object.defineProperty(window, 'print', { configurable: true, writable: true, value: print });
});
afterEach(() => {
  act(() => clearPrintRoot());
});

describe('printDocument', () => {
  it('mounts a light-token print root under <body> and opens the print dialog', async () => {
    let ok = false;
    await act(async () => {
      ok = await printDocument(doc());
    });
    expect(ok).toBe(true);
    expect(print).toHaveBeenCalledTimes(1);
    const root = document.getElementById(PRINT_ROOT_ID)!;
    expect(root.parentElement).toBe(document.body);
    expect(root.style.getPropertyValue('--background')).toBe(REPORT_LIGHT_TOKENS.background);
    expect(root.style.getPropertyValue('--chart-1')).toBe(REPORT_LIGHT_TOKENS['chart-1']);
    expect(root.querySelector('style')?.textContent).toBe(PRINT_CSS);
    expect(PRINT_CSS).toContain('@page { size: A4');
    expect(PRINT_CSS).toContain(`body > *:not(#${PRINT_ROOT_ID}) { display: none !important; }`);
    expect(PRINT_CSS).toContain(`@media screen { #${PRINT_ROOT_ID} { display: none !important; } }`);
  });

  it('renders the whole document statically, defanged by default', async () => {
    await act(async () => {
      await printDocument(doc());
    });
    const root = document.getElementById(PRINT_ROOT_ID)!;
    expect(root.querySelector('[data-report-document="print"]')).not.toBeNull();
    expect(root).toHaveTextContent('Methodology & limitations');
    expect(root).toHaveTextContent('AI-generated; verify before acting.');
    expect(root).toHaveTextContent('Generated by Agentic SOC');
    // Static blocks: the chart's data table is visible and no block menu is offered.
    expect(root.querySelector('[data-testid="block-menu-trigger"]')).toBeNull();
    expect(root.textContent).toContain('203[.]0[.]113[.]14');
    expect(root.textContent).not.toContain('203.0.113.14');
  });

  it('keeps raw indicators when the toggle is off', async () => {
    await act(async () => {
      await printDocument(doc(), { defang: false });
    });
    expect(document.getElementById(PRINT_ROOT_ID)!.textContent).toContain('203.0.113.14');
  });

  it('unmounts after printing and replaces a pending root', async () => {
    await act(async () => {
      await printDocument(doc());
    });
    await act(async () => {
      await printDocument(doc());
    });
    expect(document.querySelectorAll(`#${PRINT_ROOT_ID}`)).toHaveLength(1);
    act(() => {
      window.dispatchEvent(new Event('afterprint'));
    });
    await waitFor(() => expect(document.getElementById(PRINT_ROOT_ID)).toBeNull());
  });
});
