// @ts-check
/**
 * Minimal, SCOPED ESLint flat config for the webui.
 *
 * The single load-bearing goal is the React Rules-of-Hooks guard:
 *   `react-hooks/rules-of-hooks` = "error".
 * That rule catches the React #310 class of bug ("Rendered more hooks than
 * during the previous render") that fires when a hook (useState, useMemo,
 * useEffect, useCallback, useRef, useId, or a custom use-prefixed hook such as
 * useAuth) runs AFTER a conditional early return in the same component —
 * exactly the pattern Wave 7's loading-skeleton early returns introduced.
 *
 * Everything else is intentionally kept quiet so this config does NOT erupt
 * with hundreds of unrelated style errors:
 *   - we do NOT extend the full recommended TS/JS rule sets,
 *   - `react-hooks/exhaustive-deps` is "warn" (not "error") to avoid flooding.
 * This is a focused hooks guard, not a full lint overhaul.
 *
 * Round-5 W0-E E4 added `eslint-plugin-jsx-a11y`: it surfaces accessibility issues
 * (missing alt text, label association, aria misuse, …) so the A11Y-PASS wave can burn
 * them down, WITHOUT breaking `npm run lint` (which must stay at 0 ERRORS beyond the
 * hooks guard). Per the file's own warn→error rollout note (DESIGN_STANDARD §12 /
 * IMPLEMENTATION E4), Round-5 polish now completes that rollout:
 *
 *   - The high-signal, now-CLEAN recommended rules (aria-* validity, role validity,
 *     alt-text, heading/anchor content, tabindex, scope, …) are promoted to "error"
 *     so a naming/aria regression FAILS the gate instead of slipping in as an advisory
 *     warning. Every rule promoted here was verified to have ZERO findings against the
 *     current source before promotion (measured with the component-map below).
 *   - Two additional WCAG-2.2-relevant rules NOT in the recommended subset — `lang`
 *     (3.1.2 language of parts) and `no-aria-hidden-on-focusable` (4.1.2, an
 *     aria-hidden focusable trap) — are added at "error" (both currently clean).
 *   - Rules that still have findings stay at "warn" with a TODO so they never block the
 *     gate: `label-has-associated-control` (shadcn `<Label>` siblings the rule can't
 *     statically associate) and the recommended `role-supports-aria-props`
 *     (LabeledSlider). `prefer-tag-over-role` (not in recommended) is left OFF to
 *     preserve the plugin's own intent (see the warn/off derivation below).
 *
 * A `settings['jsx-a11y']` component-map teaches the plugin that the wrapper
 * `<Label>`/`<Input>`/… primitives render their underlying HTML element, and
 * `polymorphicPropName: 'as'` handles the `as=` escape hatch.
 */
import reactHooks from 'eslint-plugin-react-hooks';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    // Only lint the app source; ignore build output, deps, configs, and the
    // auto-generated OpenAPI types (Coupling-F; regenerated by `npm run gen:types`,
    // never hand-edited — linting it is noise and would flag generated idioms).
    ignores: [
      'dist/**',
      'node_modules/**',
      'coverage/**',
      '*.config.{js,ts}',
      'src/lib/api-types.gen.ts',
    ],
  },
  {
    files: ['src/**/*.{ts,tsx}'],
    // Don't flag pre-existing `// eslint-disable …` comments as unused just
    // because this scoped config doesn't enable the rule they silence.
    linterOptions: {
      reportUnusedDisableDirectives: 'off',
    },
    // Teach jsx-a11y about the shadcn/Radix wrapper primitives so label/aria rules
    // resolve against the real underlying HTML element (not an unknown component),
    // and honour the `as=` polymorphic escape hatch.
    settings: {
      'jsx-a11y': {
        polymorphicPropName: 'as',
        components: {
          Label: 'label',
          Input: 'input',
          Textarea: 'textarea',
          Select: 'select',
          Button: 'button',
          Checkbox: 'input',
          Switch: 'input',
          Slider: 'input',
          RadioGroup: 'input',
        },
      },
    },
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: { jsx: true },
      },
    },
    plugins: {
      'react-hooks': reactHooks,
      // Accessibility lint (W0-E E4) — surfaces a11y issues as advisory warnings.
      'jsx-a11y': jsxA11y,
      // Registered so the codebase's existing inline
      // `// eslint-disable-next-line @typescript-eslint/...` directives resolve
      // to a known rule (otherwise ESLint 9 errors on the unknown rule name).
      // The rules below are deliberately left OFF — this config is a hooks
      // guard, not a TypeScript style overhaul.
      '@typescript-eslint': tseslint.plugin,
    },
    rules: {
      // THE guard — keep this as an error forever.
      'react-hooks/rules-of-hooks': 'error',
      // Helpful but noisy; warn-only so it never blocks and never floods.
      'react-hooks/exhaustive-deps': 'warn',
      // Accessibility: the plugin's recommended rule set, downgraded to WARN so the
      // lint gate stays at 0 ERRORS (only rules-of-hooks is an error). This spreads the
      // recommended config's rules and forces every one to "warn" (the recommended set
      // marks some as "error"; we do not want those to break `npm run lint` yet).
      //
      // Preserve the plugin's own intent: rules the recommended config sets to
      // 'off' stay OFF (the plugin turns OFF its DEPRECATED rules — e.g.
      // `label-has-for`, superseded by `label-has-associated-control`). Blanket-
      // forcing EVERY key to 'warn' resurrected those deprecated rules and made
      // them fire false positives on correctly-associated `htmlFor`/`id` labels.
      // We downgrade the ENABLED recommended rules ('error'→'warn') and keep the
      // 'off' ones off.
      ...Object.fromEntries(
        Object.entries(jsxA11y.configs.recommended.rules).map(([rule, setting]) => {
          const level = Array.isArray(setting) ? setting[0] : setting;
          return [rule, level === 'off' || level === 0 ? 'off' : 'warn'];
        }),
      ),
      // --- WCAG warn→error rollout (Round-5 polish) -------------------------------
      // These high-signal a11y rules are CLEAN against the current source (verified:
      // 0 findings with the component-map above), so they are promoted from the
      // recommended 'warn' to 'error' — a future aria/naming regression now FAILS the
      // lint gate instead of slipping in as an advisory warning. If any of these ever
      // needs to go back to 'warn', do it deliberately (do NOT delete the rule).
      'jsx-a11y/alt-text': 'error',
      'jsx-a11y/img-redundant-alt': 'error',
      'jsx-a11y/aria-props': 'error',
      'jsx-a11y/aria-proptypes': 'error',
      'jsx-a11y/aria-role': 'error',
      'jsx-a11y/aria-unsupported-elements': 'error',
      'jsx-a11y/aria-activedescendant-has-tabindex': 'error',
      'jsx-a11y/role-has-required-aria-props': 'error',
      'jsx-a11y/heading-has-content': 'error',
      'jsx-a11y/anchor-has-content': 'error',
      'jsx-a11y/html-has-lang': 'error',
      'jsx-a11y/iframe-has-title': 'error',
      'jsx-a11y/tabindex-no-positive': 'error',
      'jsx-a11y/scope': 'error',
      'jsx-a11y/no-redundant-roles': 'error',
      'jsx-a11y/no-access-key': 'error',
      'jsx-a11y/autocomplete-valid': 'error',
      'jsx-a11y/no-distracting-elements': 'error',
      // Two WCAG-2.2-relevant rules NOT in the recommended subset, both currently
      // clean → added at 'error': `lang` (3.1.2 language of parts) and
      // `no-aria-hidden-on-focusable` (4.1.2 — aria-hidden on a focusable element
      // hides it from AT while it still takes focus, a keyboard trap).
      'jsx-a11y/lang': 'error',
      'jsx-a11y/no-aria-hidden-on-focusable': 'error',
      // `label-has-associated-control` is OFF by design: it cannot statically follow
      // our labeling patterns (the `Field` wrapper's programmatic aria wiring + the
      // shadcn `<Label htmlFor>`/`<Input id>` sibling pattern), so it only emits false
      // positives here. Real label association is enforced by the `Field` primitive and
      // proven by the jest-axe specs on the load-bearing surfaces — that is the source
      // of truth, not this rule. Do NOT re-enable without a component-aware config.
      'jsx-a11y/label-has-associated-control': 'off',
      // Kept at 'warn' (1 finding, LabeledSlider) — surfaces without blocking the gate.
      'jsx-a11y/role-supports-aria-props': 'warn',
      // `prefer-tag-over-role` (not in the recommended set, ~41 findings) stays OFF to
      // preserve the plugin's own default intent; enable+burn-down in a later wave.
      'jsx-a11y/prefer-tag-over-role': 'off',
      // Off (registered only so existing disable-directives are recognised).
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
    },
  },
  {
    // Chat revamp G1 (SPEC §7.1, BLOCKS.md §5.1): every chat and report string is a React
    // text node. Model, log and source text reaches these surfaces, so raw HTML injection
    // is banned outright here, in every spelling: the JSX attribute; the props-object key
    // and member access (`{ dangerouslySetInnerHTML }`, `p.dangerouslySetInnerHTML`) as an
    // Identifier; and the quoted / computed forms (`{ 'dangerouslySetInnerHTML': … }`,
    // `p['dangerouslySetInnerHTML']`) as a string Literal. Comments are not AST nodes.
    files: ['src/soc/chat/**/*.{ts,tsx}', 'src/soc/reports/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: "JSXAttribute[name.name='dangerouslySetInnerHTML']",
          message: 'G1: chat and report strings render as React text nodes only; dangerouslySetInnerHTML is banned here.',
        },
        {
          selector: "Identifier[name='dangerouslySetInnerHTML']",
          message: 'G1: chat and report strings render as React text nodes only; dangerouslySetInnerHTML is banned here.',
        },
        {
          selector: "Literal[value='dangerouslySetInnerHTML']",
          message: 'G1: chat and report strings render as React text nodes only; dangerouslySetInnerHTML is banned here.',
        },
      ],
    },
  },
);
